version: '3.8'

services:
  ngnix:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - planit
  planit:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "8089:8089"
    env_file:
      - .env
    command: ["uvicorn", "app.main:app","--host", "0.0.0.0", "--port", "8089","--workers", "4"]