version: '3.8'

services:
  planit:
    build: .
    volumes:
      - ./:/usr/src/app
    ports:
      - "8089:8089"
    env_file:
      - .env
    command: ["uvicorn", "app.main:app","--host", "0.0.0.0", "--port", "8089","--reload"]